<option value="Administrative and Support Service">Administrative and Support Service</option>
<option value="Agriculture, Forestry and Fishing">Agriculture, Forestry and Fishing</option>
<option value="Art, Entertainment and Recreation">Art, Entertainment and Recreation</option>
<option value="Construction">Construction</option>
<option value="Education">Education</option>
<option value="Electricity, Gas, Steam, and Air Conditioning Supply">Electricity, Gas, Steam, and Air Conditioning Supply</option>
<option value="Banking and Finance">Banking and Finance</option>
<option value="Human Health and Social Work Activities">Human Health and Social Work Activities</option>
<option value="Information and Communication">Information and Communication Technology</option>
<option value="Manufacturing">Manufacturing</option>
<option value="Mining and Quarrying">Mining and Quarrying</option>
<option value="Professional, Scientific and Technical Activities">Professional, Scientific and Technical Activities</option>
<option value="Public Administration and Defence">Public Administration and Defence</option>
<option value="Real Estate Activities">Real Estate Activities</option>
<option value="Transportation and Storage">Transportation and Storage</option>
<option value="Water Supply, Sewerage, Waste Management">Water Supply, Sewerage, Waste Management</option>
<option value="Wholesale and Retail Trade">Wholesale and Retail Trade</option>
<option value="Others">Others</option>