package com.utils;

import java.util.ArrayList;
import java.util.List;
import java.util.Locale;

public class SelectionUtils {
	public static List<String> getIndustrySelections() {
		List<String> list = new ArrayList<>();
		list.add("Administrative and Support Service");
		list.add("Agriculture, Forestry and Fishing");
		list.add("Art, Entertainment and Recreation");
		list.add("Construction");
		list.add("Education");
		list.add("Electricity, Gas, Steam, and Air Conditioning Supply");
		list.add("Banking and Finance");
		list.add("Human Health and Social Work Activities");
		list.add("Information and Communication Technology");
		list.add("Manufacturing");
		list.add("Mining and Quarrying");
		list.add("Professional, Scientific and Technical Activities");
		list.add("Public Administration and Defence");
		list.add("Real Estate Activities");
		list.add("Transportation and Storage");
		list.add("Water Supply, Sewerage, Waste Management");
		list.add("Wholesale and Retail Trade");
		list.add("Others");
		return list;
	}

	public static List<String> getRaceSelections() {
		List<String> list = new ArrayList<>();
		list.add("Chinese");
		list.add("Malay");
		list.add("Indian");
		list.add("Others");
		return list;
	}

	public static List<String> getMaritalStatusSelections() {
		List<String> list = new ArrayList<>();
		list.add("Single");
		list.add("Married");
		list.add("Divorced");
		list.add("Widowed");
		return list;
	}

	public static List<String> getSalutationSelections() {
		List<String> list = new ArrayList<>();
		list.add("Dr.");
		list.add("Mr.");
		list.add("Mrs.");
		list.add("Ms.");
		list.add("Madam.");
		return list;
	}

	public static List<String> getCountrySelections() {
		List<String> list = new ArrayList<>();
		list.add("Afghanistan");
		list.add("Åland Islands");
		list.add("Albania");
		list.add("Algeria");
		list.add("American Samoa");
		list.add("Andorra");
		list.add("Angola");
		list.add("Anguilla");
		list.add("Antarctica");
		list.add("Antigua and Barbuda");
		list.add("Argentina");
		list.add("Armenia");
		list.add("Aruba");
		list.add("Australia");
		list.add("Austria");
		list.add("Azerbaijan");
		list.add("Bahamas");
		list.add("Bahrain");
		list.add("Bangladesh");
		list.add("Barbados");
		list.add("Belarus");
		list.add("Belgium");
		list.add("Belize");
		list.add("Benin");
		list.add("Bermuda");
		list.add("Bhutan");
		list.add("Bolivia");
		list.add("Bosnia and Herzegovina");
		list.add("Botswana");
		list.add("Bouvet Island");
		list.add("Brazil");
		list.add("British Indian Ocean Territory");
		list.add("Brunei Darussalam");
		list.add("Bulgaria");
		list.add("Burkina Faso");
		list.add("Burundi");
		list.add("Cambodia");
		list.add("Cameroon");
		list.add("Canada");
		list.add("Cape Verde");
		list.add("Cayman Islands");
		list.add("Central African Republic");
		list.add("Chad");
		list.add("Chile");
		list.add("China");
		list.add("Christmas Island");
		list.add("Cocos (Keeling) Islands");
		list.add("Colombia");
		list.add("Comoros");
		list.add("Congo");
		list.add("Congo, The Democratic Republic of The");
		list.add("Cook Islands");
		list.add("Costa Rica");
		list.add("Cote D'ivoire");
		list.add("Croatia");
		list.add("Cuba");
		list.add("Cyprus");
		list.add("Czech Republic");
		list.add("Denmark");
		list.add("Djibouti");
		list.add("Dominica");
		list.add("Dominican Republic");
		list.add("Ecuador");
		list.add("Egypt");
		list.add("El Salvador");
		list.add("Equatorial Guinea");
		list.add("Eritrea");
		list.add("Estonia");
		list.add("Ethiopia");
		list.add("Falkland Islands (Malvinas)");
		list.add("Faroe Islands");
		list.add("Fiji");
		list.add("Finland");
		list.add("France");
		list.add("French Guiana");
		list.add("French Polynesia");
		list.add("French Southern Territories");
		list.add("Gabon");
		list.add("Gambia");
		list.add("Georgia");
		list.add("Germany");
		list.add("Ghana");
		list.add("Gibraltar");
		list.add("Greece");
		list.add("Greenland");
		list.add("Grenada");
		list.add("Guadeloupe");
		list.add("Guam");
		list.add("Guatemala");
		list.add("Guernsey");
		list.add("Guinea");
		list.add("Guinea-bissau");
		list.add("Guyana");
		list.add("Haiti");
		list.add("Heard Island and Mcdonald Islands");
		list.add("Holy See (Vatican City State)");
		list.add("Honduras");
		list.add("Hong Kong");
		list.add("Hungary");
		list.add("Iceland");
		list.add("India");
		list.add("Indonesia");
		list.add("Iran, Islamic Republic of");
		list.add("Iraq");
		list.add("Ireland");
		list.add("Isle of Man");
		list.add("Israel");
		list.add("Italy");
		list.add("Jamaica");
		list.add("Japan");
		list.add("Jersey");
		list.add("Jordan");
		list.add("Kazakhstan");
		list.add("Kenya");
		list.add("Kiribati");
		list.add("Korea, Democratic People's Republic of");
		list.add("Korea, Republic of");
		list.add("Kuwait");
		list.add("Kyrgyzstan");
		list.add("Lao People's Democratic Republic");
		list.add("Latvia");
		list.add("Lebanon");
		list.add("Lesotho");
		list.add("Liberia");
		list.add("Libyan Arab Jamahiriya");
		list.add("Liechtenstein");
		list.add("Lithuania");
		list.add("Luxembourg");
		list.add("Macao");
		list.add("Macedonia, The Former Yugoslav Republic of");
		list.add("Madagascar");
		list.add("Malawi");
		list.add("Malaysia");
		list.add("Maldives");
		list.add("Mali");
		list.add("Malta");
		list.add("Marshall Islands");
		list.add("Martinique");
		list.add("Mauritania");
		list.add("Mauritius");
		list.add("Mayotte");
		list.add("Mexico");
		list.add("Micronesia, Federated States of");
		list.add("Moldova, Republic of");
		list.add("Monaco");
		list.add("Mongolia");
		list.add("Montenegro");
		list.add("Montserrat");
		list.add("Morocco");
		list.add("Mozambique");
		list.add("Myanmar");
		list.add("Namibia");
		list.add("Nauru");
		list.add("Nepal");
		list.add("Netherlands");
		list.add("Netherlands Antilles");
		list.add("New Caledonia");
		list.add("New Zealand");
		list.add("Nicaragua");
		list.add("Niger");
		list.add("Nigeria");
		list.add("Niue");
		list.add("Norfolk Island");
		list.add("Northern Mariana Islands");
		list.add("Norway");
		list.add("Oman");
		list.add("Pakistan");
		list.add("Palau");
		list.add("Palestinian Territory, Occupied");
		list.add("Panama");
		list.add("Papua New Guinea");
		list.add("Paraguay");
		list.add("Peru");
		list.add("Philippines");
		list.add("Pitcairn");
		list.add("Poland");
		list.add("Portugal");
		list.add("Puerto Rico");
		list.add("Qatar");
		list.add("Reunion");
		list.add("Romania");
		list.add("Russian Federation");
		list.add("Rwanda");
		list.add("Saint Helena");
		list.add("Saint Kitts and Nevis");
		list.add("Saint Lucia");
		list.add("Saint Pierre and Miquelon");
		list.add("Saint Vincent and The Grenadines");
		list.add("Samoa");
		list.add("San Marino");
		list.add("Sao Tome and Principe");
		list.add("Saudi Arabia");
		list.add("Senegal");
		list.add("Serbia");
		list.add("Seychelles");
		list.add("Sierra Leone");
		list.add("Singapore");
		list.add("Slovakia");
		list.add("Slovenia");
		list.add("Solomon Islands");
		list.add("Somalia");
		list.add("South Africa");
		list.add("South Georgia and The South Sandwich Islands");
		list.add("Spain");
		list.add("Sri Lanka");
		list.add("Sudan");
		list.add("Suriname");
		list.add("Svalbard and Jan Mayen");
		list.add("Swaziland");
		list.add("Sweden");
		list.add("Switzerland");
		list.add("Syrian Arab Republic");
		list.add("Taiwan");
		list.add("Tajikistan");
		list.add("Tanzania, United Republic of");
		list.add("Thailand");
		list.add("Timor-leste");
		list.add("Togo");
		list.add("Tokelau");
		list.add("Tonga");
		list.add("Trinidad and Tobago");
		list.add("Tunisia");
		list.add("Turkey");
		list.add("Turkmenistan");
		list.add("Turks and Caicos Islands");
		list.add("Tuvalu");
		list.add("Uganda");
		list.add("Ukraine");
		list.add("United Arab Emirates");
		list.add("United Kingdom");
		list.add("United States");
		list.add("United States Minor Outlying Islands");
		list.add("Uruguay");
		list.add("Uzbekistan");
		list.add("Vanuatu");
		list.add("Venezuela");
		list.add("Viet Nam");
		list.add("Virgin Islands, British");
		list.add("Virgin Islands, U.S.");
		list.add("Wallis and Futuna");
		list.add("Western Sahara");
		list.add("Yemen");
		list.add("Zambia");
		list.add("Zimbabwe");
		return list;
	}

	public static List<String> getNationalitySelections() {
		List<String> list = new ArrayList<>();
		list.add("Afghan");
		list.add("Albanian");
		list.add("Algerian");
		list.add("American");
		list.add("Andorran");
		list.add("Angolan");
		list.add("Antiguans");
		list.add("Argentinean");
		list.add("Armenian");
		list.add("Australian");
		list.add("Austrian");
		list.add("Azerbaijani");
		list.add("Bahamian");
		list.add("Bahraini");
		list.add("Bangladeshi");
		list.add("Barbadian");
		list.add("Barbudans");
		list.add("Batswana");
		list.add("Belarusian");
		list.add("Belgian");
		list.add("Belizean");
		list.add("Beninese");
		list.add("Bhutanese");
		list.add("Bolivian");
		list.add("Bosnian");
		list.add("Brazilian");
		list.add("British");
		list.add("Bruneian");
		list.add("Bulgarian");
		list.add("Burkinabe");
		list.add("Burmese");
		list.add("Burundian");
		list.add("Cambodian");
		list.add("Cameroonian");
		list.add("Canadian");
		list.add("Cape Verdean");
		list.add("Central African");
		list.add("Chadian");
		list.add("Chilean");
		list.add("Chinese");
		list.add("Colombian");
		list.add("Comoran");
		list.add("Congolese");
		list.add("Costa Rican");
		list.add("Croatian");
		list.add("Cuban");
		list.add("Cypriot");
		list.add("Czech");
		list.add("Danish");
		list.add("Djibouti");
		list.add("Dominican");
		list.add("Dutch");
		list.add("East Timorese");
		list.add("Ecuadorean");
		list.add("Egyptian");
		list.add("Emirian");
		list.add("Equatorial Guinean");
		list.add("Eritrean");
		list.add("Estonian");
		list.add("Ethiopian");
		list.add("Fijian");
		list.add("Filipino");
		list.add("Finnish");
		list.add("French");
		list.add("Gabonese");
		list.add("Gambian");
		list.add("Georgian");
		list.add("German");
		list.add("Ghanaian");
		list.add("Greek");
		list.add("Grenadian");
		list.add("Guatemalan");
		list.add("Guinea-Bissauan");
		list.add("Guinean");
		list.add("Guyanese");
		list.add("Haitian");
		list.add("Herzegovinian");
		list.add("Honduran");
		list.add("Hungarian");
		list.add("Icelander");
		list.add("Indian");
		list.add("Indonesian");
		list.add("Iranian");
		list.add("Iraqi");
		list.add("Irish");
		list.add("Israeli");
		list.add("Italian");
		list.add("Ivorian");
		list.add("Jamaican");
		list.add("Japanese");
		list.add("Jordanian");
		list.add("Kazakhstani");
		list.add("Kenyan");
		list.add("Kittian and Nevisian");
		list.add("Kuwaiti");
		list.add("Kyrgyz");
		list.add("Laotian");
		list.add("Latvian");
		list.add("Lebanese");
		list.add("Liberian");
		list.add("Libyan");
		list.add("Liechtensteiner");
		list.add("Lithuanian");
		list.add("Luxembourger");
		list.add("Macedonian");
		list.add("Malagasy");
		list.add("Malawian");
		list.add("Malaysian");
		list.add("Maldivan");
		list.add("Malian");
		list.add("Maltese");
		list.add("Marshallese");
		list.add("Mauritanian");
		list.add("Mauritian");
		list.add("Mexican");
		list.add("Micronesian");
		list.add("Moldovan");
		list.add("Monacan");
		list.add("Mongolian");
		list.add("Moroccan");
		list.add("Mosotho");
		list.add("Motswana");
		list.add("Mozambican");
		list.add("Namibian");
		list.add("Nauruan");
		list.add("Nepalese");
		list.add("New Zealander");
		list.add("Ni-Vanuatu");
		list.add("Nicaraguan");
		list.add("Nigerien");
		list.add("North Korean");
		list.add("Northern Irish");
		list.add("Norwegian");
		list.add("Omani");
		list.add("Pakistani");
		list.add("Palauan");
		list.add("Panamanian");
		list.add("Papua New Guinean");
		list.add("Paraguayan");
		list.add("Peruvian");
		list.add("Polish");
		list.add("Portuguese");
		list.add("Qatari");
		list.add("Romanian");
		list.add("Russian");
		list.add("Rwandan");
		list.add("Saint Lucian");
		list.add("Salvadoran");
		list.add("Samoan");
		list.add("San Marinese");
		list.add("Sao Tomean");
		list.add("Saudi");
		list.add("Scottish");
		list.add("Senegalese");
		list.add("Serbian");
		list.add("Seychellois");
		list.add("Sierra Leonean");
		list.add("Singaporean");
		list.add("Slovakian");
		list.add("Slovenian");
		list.add("Solomon Islander");
		list.add("Somali");
		list.add("South African");
		list.add("South Korean");
		list.add("Spanish");
		list.add("Sri Lankan");
		list.add("Sudanese");
		list.add("Surinamer");
		list.add("Swazi");
		list.add("Swedish");
		list.add("Swiss");
		list.add("Syrian");
		list.add("Taiwanese");
		list.add("Tajik");
		list.add("Tanzanian");
		list.add("Thai");
		list.add("Togolese");
		list.add("Tongan");
		list.add("Trinidadian or Tobagonian");
		list.add("Tunisian");
		list.add("Turkish");
		list.add("Tuvaluan");
		list.add("Ugandan");
		list.add("Ukrainian");
		list.add("Uruguayan");
		list.add("Uzbekistani");
		list.add("Venezuelan");
		list.add("Vietnamese");
		list.add("Welsh");
		list.add("Yemenite");
		list.add("Zambian");
		list.add("Zimbabwean");
		return list;
	}
}
